### ISSUE TITLE
[Login][varios login]

### ISSUE THREAD

**Issue by josdurgar1** [espcrusue/Deliberaciones#2]
-Actualmente existen varias formas de "logueo" implementadas en el sistema cuando sólo debería de haber una, la cual debería de estar integrada con el módulo de "Autenticación" y no con "Censo" como está actualmente.

-En el welcome de la aplicación aparecen 2 tipos de login.

-Solo tiene que existir un login integrado con "Autenticacion".

**Comment by mjpalma** [comment]
Esta incidencia no se ha atendido por falta de tiempo.
